import './components/tabs'
import './components/login'
import './components/elements'
import './components/registration'
import './components/calendar'
import './components/notes'
import './components/table'
